# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1991a549c64c99a8994948ff64c04b8fabfc7464e711298a3a8a436b5ffebf3c2300ae24dd472b0178ae0f45382417784af1590ccbc91a76ea6b5696b22f3e2b

test:
  secret_key_base: 8667dcc8b771d617cefdd21a792cad24c197e7156ca12683e6dead4f35599bf234915dc58092f7f6b2d443ceb925513645cd39125d55adb94a1170bad6fa7ed3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
